import os
import re

filepath = r'a:\constitution\backend\alembic\versions\aaad793a638b_initial_tables.py'

with open(filepath, 'r') as f:
    content = f.read()

# Replace upgrade
upgrade_match = re.search(r'(def upgrade\(\) -> None:.*?op\.create_index\(op\.f\(\'ix_complaints_title\'\), \'complaints\', \[\'title\'\], unique=False\))', content, re.DOTALL)
new_upgrade = upgrade_match.group(1) + "\n    # ### end Alembic commands ###"

# New downgrade
new_downgrade = '''def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_title'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_id'), table_name='complaints')
    op.drop_index('idx_complaints_geom', table_name='complaints', postgresql_using='gist')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
'''

new_content = re.sub(r'def upgrade\(\) -> None:.*?(?=def downgrade\(\) -> None:)', new_upgrade + '\n\n\n', content, flags=re.DOTALL)
new_content = re.sub(r'def downgrade\(\) -> None:.*', new_downgrade, new_content, flags=re.DOTALL)

with open(filepath, 'w') as f:
    f.write(new_content)

print('Done')
